/* Griz HQ scoreboard — cache-authoritative renderer. */
/* Team identity is keyed to canonical ESPN IDs so Montana (149) and Montana State (147) can never cross-match. */
(function(){
'use strict';
const C=window.GRIZ_SCOREBOARD_CONFIG||{season:2026,weeks:[['2026-08-27','2026-08-30','WEEK 0 • AUG 27–30'],['2026-09-03','2026-09-06','WEEK 1 • SEP 3–6'],['2026-09-10','2026-09-13','WEEK 2 • SEP 10–13'],['2026-09-17','2026-09-20','WEEK 3 • SEP 17–20'],['2026-09-24','2026-09-27','WEEK 4 • SEP 24–27'],['2026-10-01','2026-10-04','WEEK 5 • OCT 1–4'],['2026-10-08','2026-10-11','WEEK 6 • OCT 8–11'],['2026-10-15','2026-10-18','WEEK 7 • OCT 15–18'],['2026-10-22','2026-10-25','WEEK 8 • OCT 22–25'],['2026-10-29','2026-11-01','WEEK 9 • OCT 29–NOV 1'],['2026-11-05','2026-11-08','WEEK 10 • NOV 5–8'],['2026-11-12','2026-11-15','WEEK 11 • NOV 12–15'],['2026-11-19','2026-11-22','WEEK 12 • NOV 19–22']]};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s||'').replace(/\s*\([^)]*\)\s*$/,'').replace(/\s+/g,' ').trim();
const norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9]/g,'');
const tokens=s=>clean(s).toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').trim().split(/\s+/).filter(Boolean);
const teamName=t=>t?.name||t?.short||t?.displayName||'Team';
const teamNames=t=>[t?.name,t?.short,t?.displayName,t?.abbreviation].filter(Boolean);
const teams=e=>Array.isArray(e?.teams)?e.teams:(Array.isArray(e?.competitors)?e.competitors:[]);
const CANONICAL_TEAM_IDS={'Montana':'149','Montana State':'147','South Dakota State':'2571','South Dakota':'233','Idaho':'70','Idaho State':'304','Northern Arizona':'2464','Stetson':'56','Stephen F. Austin':'2617'}; const canonicalId=n=>CANONICAL_TEAM_IDS[clean(n)]||''; const logo=t=>{const id=String(t?.id||''); const canonical=canonicalId(teamName(t)); const logoId=canonical||id; return t?.logo&&(!canonical||id===canonical)?t.logo:(t?.logos?.[0]?.href&&(!canonical||id===canonical)?t.logos[0].href:(logoId?`https://a.espncdn.com/i/teamlogos/ncaa/500/${encodeURIComponent(logoId)}.png`:''));};
const status=e=>{const s=e?.status||{};if(s.completed||s.state==='post'||s.name==='STATUS_FINAL')return'FINAL';if(s.state==='in'||s.name==='STATUS_IN_PROGRESS')return s.shortDetail||'LIVE';return s.shortDetail||s.detail||'SCHEDULED';};
const fmt=s=>new Date(String(s).slice(0,10)+'T12:00:00Z').toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'});
// Exact team identity first. Never treat "Montana" as "Montana State".
const rankForTeam=(t,rankings)=>{const id=String(t?.id||'');const canonical=Object.keys(CANONICAL_TEAM_IDS).find(n=>CANONICAL_TEAM_IDS[n]===id);if(canonical){const exactCanonical=rankings.find(r=>norm(r.team||r.name||'')===norm(canonical));if(exactCanonical)return exactCanonical.rank||'';}const names=teamNames(t);const exact=rankings.find(r=>{const rn=norm(r.team||r.name||'');return names.some(n=>norm(n)===rn);});if(exact)return exact.rank||'';const actuals=names.map(norm);const candidates=rankings.filter(r=>{const rn=norm(r.team||r.name||'');return actuals.some(a=>a===rn||a.startsWith(rn));});return candidates.length?candidates.sort((a,b)=>norm(b.team||b.name||'').length-norm(a.team||a.name||'').length)[0].rank||'':'';};
const card=(e,rankings=[])=>{const ts=teams(e),a=ts.find(t=>t.homeAway==='away')||ts[0],h=ts.find(t=>t.homeAway==='home')||ts[1];if(!a||!h)return'';const row=t=>{const rank=rankForTeam(t,rankings);return `<div class="ghq-score-team"><span class="ghq-score-team-name">${rank?`<span class="ghq-score-rank">#${esc(rank)}</span>`:''}${logo(t)?`<img src="${esc(logo(t))}" alt="" loading="lazy" style="width:44px;height:44px;object-fit:contain">`:''}<span>${esc(teamName(t))}</span></span><strong>${esc(t?.score??'—')}</strong></div>`;};const href=` href="${/^\d+$/.test(String(e.id||''))?'https://www.espn.com/college-football/game/_/gameId/'+encodeURIComponent(e.id):'https://www.espn.com/college-football/scoreboard/_/week/3/year/2026/seasontype/2'}" target="_blank" rel="noopener"`;return`<a class="ghq-score-card"${href}><div class="ghq-score-meta"><span>${esc(fmt(e.date))}</span><b>${esc(e.source||'ESPN')}</b></div>${row(a)}${row(h)}<div class="ghq-score-status">${esc(status(e))}</div></a>`;};
const empty=(rank,nm,bye)=>`<div class="ghq-score-card ghq-score-empty"><div class="ghq-score-meta"><b>#${esc(rank)}</b><span>${esc(nm)}</span></div><div class="ghq-score-status">${bye?'BYE — NO GAME THIS WEEK':'NO VERIFIED MATCHUP FOUND'}</div></div>`;
const weekIndex=()=>{const now=new Date().toISOString().slice(0,10),a=C.weeks.findIndex(w=>now>=w[0]&&now<=w[1]);if(a>=0)return a;const u=C.weeks.findIndex(w=>w[0]>now);return u>=0?u:C.weeks.length-1;};
async function loadCache(){if(window.GRIZ_SCOREBOARD_DATA&&Array.isArray(window.GRIZ_SCOREBOARD_DATA.weeks)&&Array.isArray(window.GRIZ_SCOREBOARD_DATA.rankings))return window.GRIZ_SCOREBOARD_DATA;const url='scoreboard/scoreboard-data.json?cache='+Date.now();const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(!Array.isArray(d.weeks)||!Array.isArray(d.rankings))throw Error('invalid scoreboard cache');window.GRIZ_SCOREBOARD_DATA=d;return d;}
function gameForRank(name,games){const canonical=Object.keys(CANONICAL_TEAM_IDS).find(n=>norm(n)===norm(name));if(canonical){const id=CANONICAL_TEAM_IDS[canonical];for(const g of games){for(const t of teams(g)){if(String(t?.id||'')===id)return g;}}}const wanted=tokens(name);for(const g of games){for(const t of teams(g)){for(const n of teamNames(t)){if(norm(n)===norm(name))return g;}}}for(const g of games){for(const t of teams(g)){const tn=tokens(teamName(t));if(tn.length>=wanted.length&&wanted.every((v,i)=>tn[i]===v))return g;}}return null;}async function render(){const weekEl=$('fcs-week-filter'),top=$('fcs-top20'),big=$('bigsky-score-games'),st=$('fcs-status');if(!weekEl||!top||!big)return;if(!weekEl.dataset.ready){C.weeks.forEach((w,i)=>{const o=document.createElement('option');o.value=i;o.textContent=w[2];weekEl.appendChild(o);});weekEl.dataset.ready='1';}if(!weekEl.dataset.userChanged)weekEl.value=String(weekIndex());const index=Number(weekEl.value)||0,w=C.weeks[index];top.innerHTML='<div class="ghq-score-empty">Loading verified scoreboard cache…</div>';big.innerHTML='';if(st)st.textContent='Loading verified scoreboard cache…';try{const d=await loadCache(),cached=d.weeks.find(x=>Number(x.index)===index)||d.weeks[index];if(!cached)throw Error('week '+index+' missing from cache');const rankings=d.rankings.slice(0,25),fcsGames=Array.isArray(cached.fcsTop25Games)?cached.fcsTop25Games:(Array.isArray(cached.fcsGames)?cached.fcsGames:(Array.isArray(cached.events)?cached.events:[])),bs=Array.isArray(cached.bigSkyGames)?cached.bigSkyGames:(Array.isArray(cached.bigSkyEvents)?cached.bigSkyEvents:[]),games=Array.from(new Map([...fcsGames,...bs].filter(g=>g&&g.id!=null).map(g=>[String(g.id),g])).values()),byeNames=new Set((cached.fcsTop25Byes||[]).map(r=>norm(r.team||r.name||'')));top.innerHTML=rankings.map((r,i)=>{const nm=r.team||r.name||'',e=gameForRank(nm,games);return e?card(e,rankings):empty(r.rank||i+1,nm,byeNames.has(norm(nm)));}).join('');const rd=$('fcs-rankings-date');if(rd)rd.textContent=cached.rankingsDate?'Stats Perform • '+cached.rankingsDate:'Stats Perform';big.innerHTML=bs.length?bs.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(e=>card(e,rankings)).join(''):'<div class="ghq-score-empty">NO BIG SKY GAMES THIS WEEK</div>';if(st)st.textContent=`Loaded authoritative cache • ${fcsGames.length} FCS games • ${bs.length} Big Sky games • ${cached.label||w[2]}`;}catch(err){top.innerHTML='<div class="ghq-score-empty"><b>SCOREBOARD CACHE UNAVAILABLE</b><span>The authoritative scoreboard cache could not be loaded. No fallback schedule is being substituted.</span></div>';big.innerHTML='<div class="ghq-score-empty">SCOREBOARD CACHE UNAVAILABLE</div>';if(st)st.textContent='Authoritative scoreboard cache unavailable';console.error('Griz scoreboard',err);}}
window.GrizScoreboard={render};const week=$('fcs-week-filter');if(week)week.addEventListener('change',()=>{week.dataset.userChanged='1';render();});render();})();
