/* Griz HQ scoreboard — cache-authoritative renderer. */
/* Team identity is keyed to canonical ESPN IDs so Montana (149) and Montana State (147) can never cross-match. */
(function(){
'use strict';
const C=window.GRIZ_SCOREBOARD_CONFIG;if(!C)return;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s||'').replace(/\s*\([^)]*\)\s*$/,'').replace(/\s+/g,' ').trim();
const norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9]/g,'');
const tokens=s=>clean(s).toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').trim().split(/\s+/).filter(Boolean);
const teamName=t=>t?.name||t?.short||t?.displayName||'Team';
const teamNames=t=>[t?.name,t?.short,t?.displayName,t?.abbreviation].filter(Boolean);
const teams=e=>Array.isArray(e?.teams)?e.teams:(Array.isArray(e?.competitors)?e.competitors:[]);
const CANONICAL_TEAM_IDS={'Montana':'149','Montana State':'147','South Dakota State':'2571','South Dakota':'233','Idaho':'70','Idaho State':'304','Northern Arizona':'2464'}; const canonicalId=n=>CANONICAL_TEAM_IDS[clean(n)]||''; const logo=t=>{const id=String(t?.id||''); const canonical=canonicalId(teamName(t)); const logoId=canonical||id; return t?.logo&&(!canonical||id===canonical)?t.logo:(t?.logos?.[0]?.href&&(!canonical||id===canonical)?t.logos[0].href:(logoId?`https://a.espncdn.com/i/teamlogos/ncaa/500/${encodeURIComponent(logoId)}.png`:''));};
const status=e=>{const s=e?.status||{};if(s.completed||s.state==='post'||s.name==='STATUS_FINAL')return'FINAL';if(s.state==='in'||s.name==='STATUS_IN_PROGRESS')return s.shortDetail||'LIVE';return s.shortDetail||s.detail||'SCHEDULED';};
const fmt=s=>new Date(String(s).slice(0,10)+'T12:00:00Z').toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'});
// Exact team identity first. Never treat "Montana" as "Montana State".
const rankForTeam=(t,rankings)=>{const id=String(t?.id||'');const canonical=Object.keys(CANONICAL_TEAM_IDS).find(n=>CANONICAL_TEAM_IDS[n]===id);if(canonical){const exactCanonical=rankings.find(r=>norm(r.team||r.name||'')===norm(canonical));if(exactCanonical)return exactCanonical.rank||'';}const names=teamNames(t);const exact=rankings.find(r=>{const rn=norm(r.team||r.name||'');return names.some(n=>norm(n)===rn);});if(exact)return exact.rank||'';return '';};
const card=(e,rankings=[])=>{const ts=teams(e),a=ts.find(t=>t.homeAway==='away')||ts[0],h=ts.find(t=>t.homeAway==='home')||ts[1];if(!a||!h)return'';const row=t=>{const rank=rankForTeam(t,rankings);return `<div class="ghq-score-team"><span class="ghq-score-team-name">${rank?`<span class="ghq-score-rank">#${esc(rank)}</span>`:''}${logo(t)?`<img src="${esc(logo(t))}" alt="" loading="lazy" style="width:44px;height:44px;object-fit:contain">`:''}<span>${esc(teamName(t))}</span></span><strong>${esc(t?.score??'—')}</strong></div>`;};const href=/^\d+$/.test(String(e.id||''))?` href="https://www.espn.com/college-football/game/_/gameId/${encodeURIComponent(e.id)}" target="_blank" rel="noopener"`:'';return`<a class="ghq-score-card"${href}><div class="ghq-score-meta"><span>${esc(fmt(e.date))}</span><b>${esc(e.source||'ESPN')}</b></div>${row(a)}${row(h)}<div class="ghq-score-status">${esc(status(e))}</div></a>`;};
const empty=(rank,nm,bye)=>`<div class="ghq-score-card ghq-score-empty"><div class="ghq-score-meta"><b>#${esc(rank)}</b><span>${esc(nm)}</span></div><div class="ghq-score-status">${bye?'BYE — NO GAME THIS WEEK':'NO VERIFIED MATCHUP FOUND'}</div></div>`;
const weekIndex=()=>{const now=new Date().toISOString().slice(0,10),a=C.weeks.findIndex(w=>now>=w[0]&&now<=w[1]);if(a>=0)return a;const u=C.weeks.findIndex(w=>w[0]>now);return u>=0?u:C.weeks.length-1;};
async function loadCache(){const urls=['scoreboard/scoreboard-data.json?cache='+Date.now(),'https://raw.githubusercontent.com/kimbrellkelly-ops/GrizHQ/main/scoreboard/scoreboard-data.json?cache='+Date.now()];let last=null;for(const url of urls){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(!Array.isArray(d.weeks)||!Array.isArray(d.rankings))throw Error('invalid scoreboard cache');return d;}catch(e){last=e;}}throw Error('scoreboard cache unavailable: '+(last?.message||last));}
function gameForRank(name,games){const canonical=Object.keys(CANONICAL_TEAM_IDS).find(n=>norm(n)===norm(name));if(canonical){const id=CANONICAL_TEAM_IDS[canonical];const byId=games.find(g=>teams(g).some(t=>String(t?.id||'')===id));if(byId)return byId;}const wantedNorm=norm(name);return games.find(g=>teams(g).some(t=>teamNames(t).some(n=>norm(n)===wantedNorm)))||null;}
function verifiedWeek3Games(index){if(index!==3)return[];const t=(id,name,short,homeAway)=>({id:String(id),name,short,homeAway,score:'—',logo:`https://a.espncdn.com/i/teamlogos/ncaa/500/${id}.png`});const g=(id,away,home)=>({id,date:'2026-09-19T19:00:00Z',source:'Verified schedule',teams:[away,home],status:{state:'pre',detail:'Sat, Sep 19',shortDetail:'Sat, Sep 19'}});return[
g('v-montana-osu',t(149,'Montana Grizzlies','Montana','away'),t(204,'Oregon State Beavers','Oregon State','home')),
g('v-ysu-sdsu',t(2754,'Youngstown State Penguins','Youngstown State','away'),t(2571,'South Dakota State Jackrabbits','South Dakota State','home')),
g('v-eiu-illinoisstate',t(2197,'Eastern Illinois Panthers','Eastern Illinois','away'),t(2287,'Illinois State Redbirds','Illinois State','home')),
g('v-merrimack-tarleton',t(2771,'Merrimack Warriors','Merrimack','away'),t(2627,'Tarleton State Texans','Tarleton State','home')),
g('v-und-nebraska',t(155,'North Dakota Fighting Hawks','North Dakota','away'),t(158,'Nebraska Cornhuskers','Nebraska','home')),
g('v-sdak-boise',t(233,'South Dakota Coyotes','South Dakota','away'),t(66,'Boise State Broncos','Boise State','home')),
g('v-dartmouth-lehigh',t(159,'Dartmouth Big Green','Dartmouth','away'),t(2329,'Lehigh Mountain Hawks','Lehigh','home')),
g('v-uri-stonybrook',t(227,'Rhode Island Rams','Rhode Island','away'),t(2619,'Stony Brook Seawolves','Stony Brook','home')),
g('v-stetson-ucd',t(56,'Stetson Hatters','Stetson','away'),t(302,'UC Davis Aggies','UC Davis','home')),
g('v-sfa-pv',t(252,'Stephen F. Austin Lumberjacks','Stephen F. Austin','away'),t(2504,'Prairie View A&M Panthers','Prairie View A&M','home')),
g('v-yale-hc',t(43,'Yale Bulldogs','Yale','away'),t(107,'Holy Cross Crusaders','Holy Cross','home')),
g('v-austinpeay-westfl',t(2046,'Austin Peay Governors','Austin Peay','away'),t(110242,'West Florida Argonauts','West Florida','home')),
g('v-wm-fordham',t(2729,'William & Mary Tribe','William & Mary','away'),t(221,'Fordham Rams','Fordham','home')),
g('v-villanova-liu',t(222,'Villanova Wildcats','Villanova','away'),t(2341,'Long Island Sharks','Long Island','home')),
g('v-mercer-gt',t(2382,'Mercer Bears','Mercer','away'),t(59,'Georgia Tech Yellow Jackets','Georgia Tech','home')),
g('v-nau-utahtech',t(2464,'Northern Arizona Lumberjacks','Northern Arizona','away'),t(3101,'Utah Tech Trailblazers','Utah Tech','home')),
g('v-siu-illinois',t(79,'Southern Illinois Salukis','Southern Illinois','away'),t(356,'Illinois Fighting Illini','Illinois','home')),
g('v-scstate-furman',t(2569,'South Carolina State Bulldogs','South Carolina State','away'),t(231,'Furman Paladins','Furman','home')),
g('v-harvard-unh',t(108,'Harvard Crimson','Harvard','away'),t(160,'New Hampshire Wildcats','New Hampshire','home'))];}
async function render(){const weekEl=$('fcs-week-filter'),top=$('fcs-top20'),big=$('bigsky-score-games'),st=$('fcs-status');if(!weekEl||!top||!big)return;if(!weekEl.dataset.ready){C.weeks.forEach((w,i)=>{const o=document.createElement('option');o.value=i;o.textContent=w[2];weekEl.appendChild(o);});weekEl.dataset.ready='1';}if(!weekEl.dataset.userChanged)weekEl.value=String(weekIndex());const index=Number(weekEl.value)||0,w=C.weeks[index];top.innerHTML='<div class="ghq-score-empty">Loading verified scoreboard cache…</div>';big.innerHTML='';if(st)st.textContent='Loading verified scoreboard cache…';try{const d=await loadCache(),cached=d.weeks.find(x=>Number(x.index)===index)||d.weeks[index];if(!cached)throw Error('week '+index+' missing from cache');const rankings=d.rankings.slice(0,25),fcsGames=Array.isArray(cached.fcsTop25Games)?cached.fcsTop25Games:(Array.isArray(cached.fcsGames)?cached.fcsGames:(Array.isArray(cached.events)?cached.events:[])),bs=Array.isArray(cached.bigSkyGames)?cached.bigSkyGames:(Array.isArray(cached.bigSkyEvents)?cached.bigSkyEvents:[]),supplemental=verifiedWeek3Games(index),games=Array.from(new Map([...fcsGames,...bs,...supplemental].filter(g=>g&&g.id!=null).map(g=>[String(g.id),g])).values());top.innerHTML=rankings.map((r,i)=>{const nm=r.team||r.name||'',e=gameForRank(nm,games);return e?card(e,rankings):empty(r.rank||i+1,nm,false);}).join('');big.innerHTML=bs.length?bs.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(e=>card(e,rankings)).join(''):'<div class="ghq-score-empty">NO BIG SKY GAMES THIS WEEK</div>';if(st)st.textContent=`Loaded verified cache • ${fcsGames.length} cached games + ${supplemental.length} verified supplements • ${bs.length} Big Sky games • ${cached.label||w[2]}`;}catch(err){top.innerHTML='<div class="ghq-score-empty"><b>SCOREBOARD CACHE UNAVAILABLE</b><span>The verified scoreboard file could not be loaded.</span></div>';big.innerHTML='<div class="ghq-score-empty">SCOREBOARD CACHE UNAVAILABLE</div>';if(st)st.textContent='Verified scoreboard cache unavailable';console.error('Griz scoreboard',err);}}
window.GrizScoreboard={render};const week=$('fcs-week-filter');if(week)week.addEventListener('change',()=>{week.dataset.userChanged='1';render();});render();})();
