/* Griz HQ scoreboard — cache-authoritative renderer. */
(function(){
'use strict';
const C=window.GRIZ_SCOREBOARD_CONFIG;if(!C)return;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s||'').replace(/\s*\([^)]*\)\s*$/,'').replace(/\s+/g,' ').trim();
const norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9]/g,'');
const tokens=s=>clean(s).toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').trim().split(/\s+/).filter(Boolean);
const teamName=t=>t?.name||t?.short||t?.displayName||'Team';
const teams=e=>Array.isArray(e?.teams)?e.teams:(Array.isArray(e?.competitors)?e.competitors:[]);
const logo=t=>t?.logo||(t?.logos?.[0]?.href)||(t?.id?`https://a.espncdn.com/i/teamlogos/ncaa/500/${encodeURIComponent(t.id)}.png`:'');
const status=e=>{const s=e?.status||{};if(s.completed||s.state==='post'||s.name==='STATUS_FINAL')return'FINAL';if(s.state==='in'||s.name==='STATUS_IN_PROGRESS')return s.shortDetail||'LIVE';return s.shortDetail||s.detail||'SCHEDULED';};
const fmt=s=>new Date(String(s).slice(0,10)+'T12:00:00Z').toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'});
const card=e=>{const ts=teams(e),a=ts.find(t=>t.homeAway==='away')||ts[0],h=ts.find(t=>t.homeAway==='home')||ts[1];if(!a||!h)return'';const row=t=>`<div class="ghq-score-team"><span class="ghq-score-team-name">${logo(t)?`<img src="${esc(logo(t))}" alt="" loading="lazy">`:''}<span>${esc(teamName(t))}</span></span><strong>${esc(t?.score??'—')}</strong></div>`;return`<a class="ghq-score-card" href="https://www.espn.com/college-football/game/_/gameId/${encodeURIComponent(e.id||'')}" target="_blank" rel="noopener"><div class="ghq-score-meta"><span>${esc(fmt(e.date))}</span><b>ESPN</b></div>${row(a)}${row(h)}<div class="ghq-score-status">${esc(status(e))}</div></a>`;};
const empty=(rank,nm,bye)=>`<div class="ghq-score-card ghq-score-empty"><div class="ghq-score-meta"><b>#${esc(rank)}</b><span>${esc(nm)}</span></div><div class="ghq-score-status">${bye?'BYE — NO GAME THIS WEEK':'NO MATCHUP FOUND IN VERIFIED CACHE'}</div></div>`;
const weekIndex=()=>{const now=new Date().toISOString().slice(0,10),a=C.weeks.findIndex(w=>now>=w[0]&&now<=w[1]);if(a>=0)return a;const u=C.weeks.findIndex(w=>w[0]>now);return u>=0?u:C.weeks.length-1;};
async function loadCache(){const r=await fetch('scoreboard/scoreboard-data.json?cache='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('scoreboard cache HTTP '+r.status);const d=await r.json();if(!Array.isArray(d.weeks)||!Array.isArray(d.rankings))throw Error('invalid scoreboard cache');return d;}
function gameForRank(name,games){const wanted=tokens(name),ambiguous=new Set(['montana','south dakota','idaho']);const exact=games.find(g=>teams(g).some(t=>norm(teamName(t))===norm(name)));if(exact)return exact;if(wanted.length===1&&ambiguous.has(wanted[0]))return null;return games.find(g=>teams(g).some(t=>{const actual=tokens(teamName(t));return wanted.length>0&&actual.length>=wanted.length&&wanted.every((word,i)=>actual[i]===word);}));}
async function render(){const weekEl=$('fcs-week-filter'),top=$('fcs-top20'),big=$('bigsky-score-games'),st=$('fcs-status');if(!weekEl||!top||!big)return;if(!weekEl.dataset.ready){C.weeks.forEach((w,i)=>{const o=document.createElement('option');o.value=i;o.textContent=w[2];weekEl.appendChild(o);});weekEl.dataset.ready='1';}if(!weekEl.dataset.userChanged)weekEl.value=String(weekIndex());const index=Number(weekEl.value)||0,w=C.weeks[index];top.innerHTML='<div class="ghq-score-empty">Loading verified scoreboard cache…</div>';big.innerHTML='';if(st)st.textContent='Loading verified scoreboard cache…';try{const d=await loadCache(),cached=d.weeks.find(x=>Number(x.index)===index)||d.weeks[index];if(!cached)throw Error('week '+index+' missing from cache');const rankings=d.rankings.slice(0,25),fcsGames=Array.isArray(cached.fcsTop25Games)?cached.fcsTop25Games:(Array.isArray(cached.fcsGames)?cached.fcsGames:(Array.isArray(cached.events)?cached.events:[])),bs=Array.isArray(cached.bigSkyGames)?cached.bigSkyGames:(Array.isArray(cached.bigSkyEvents)?cached.bigSkyEvents:[]),games=Array.from(new Map([...fcsGames,...bs].filter(g=>g&&g.id!=null).map(g=>[String(g.id),g])).values()),byes=new Set((cached.fcsTop25Byes||[]).map(r=>norm(r.team||r.name)));top.innerHTML=rankings.map((r,i)=>{const nm=r.team||r.name||'',e=gameForRank(nm,games);return e?card(e):empty(r.rank||i+1,nm,byes.has(norm(nm)));}).join('');big.innerHTML=bs.length?bs.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(card).join(''):'<div class="ghq-score-empty">NO BIG SKY GAMES THIS WEEK</div>';if(st)st.textContent=`Loaded verified cache • ${fcsGames.length} ranked games • ${bs.length} Big Sky games • ${cached.label||w[2]}`;}catch(err){top.innerHTML='<div class="ghq-score-empty"><b>SCOREBOARD CACHE UNAVAILABLE</b><span>The verified scoreboard file could not be loaded.</span></div>';big.innerHTML='<div class="ghq-score-empty">SCOREBOARD CACHE UNAVAILABLE</div>';if(st)st.textContent='Verified scoreboard cache unavailable';console.error('Griz scoreboard',err);}}
window.GrizScoreboard={render};const week=$('fcs-week-filter');if(week)week.addEventListener('change',()=>{week.dataset.userChanged='1';render();});render();})();
