/* Griz HQ — authoritative scoreboard renderer. Reads only local generated cache. */
(function(){
  'use strict';
  const C=window.GRIZ_SCOREBOARD_CONFIG;if(!C)return;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const clean=s=>String(s||'').replace(/\s*\([^)]*\)\s*$/,'').replace(/\s+/g,' ').trim();
  const norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9]/g,'');
  const same=(a,b)=>norm(a)===norm(b);
  const teamName=t=>t?.displayName||t?.shortDisplayName||t?.name||t?.short||t?.abbreviation||'Team';
  const logo=t=>t?.logo||(t?.id?`https://a.espncdn.com/i/teamlogos/ncaa/500/${encodeURIComponent(t.id)}.png`:'');
  const rankFor=(t,rankings)=>{const r=rankings.find(x=>same(clean(x.team),clean(teamName(t))));return r?.rank||''};
  const status=e=>{const s=e?.status||{};if(s.completed)return 'FINAL';if(s.state==='in'||s.name==='STATUS_IN_PROGRESS')return s.shortDetail||'LIVE';return s.shortDetail||s.detail||'SCHEDULED'};
  const dateText=s=>{const d=new Date(s);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})};
  function currentWeek(){const now=new Date();let i=C.weeks.findIndex(w=>now>=new Date(w[0]+'T00:00:00')&&now<=new Date(w[1]+'T23:59:59'));if(i>=0)return i;i=C.weeks.findIndex(w=>new Date(w[0]+'T00:00:00')>now);return i>=0?i:C.weeks.length-1}
  function eventCard(e,rankings){const ts=e.teams||[];const a=ts.find(t=>t.homeAway==='away')||ts[0]||{};const h=ts.find(t=>t.homeAway==='home')||ts[1]||{};const row=t=>`<div class="ghq-score-team"><div class="ghq-score-team-main">${logo(t)?`<img class="ghq-score-logo" src="${esc(logo(t))}" alt="" loading="lazy" decoding="async">`:''}<span>${rankFor(t,rankings)?`<span class="ghq-score-rank">#${esc(rankFor(t,rankings))}</span>`:''}<span class="ghq-score-team-name">${esc(teamName(t))}</span></span></div><span class="ghq-score-team-score">${esc(t.score??'—')}</span></div>`;const href=e.id?`https://www.espn.com/college-football/game/_/gameId/${encodeURIComponent(e.id)}`:'#';return `<a class="ghq-score-card" href="${href}" target="_blank" rel="noopener"><div class="ghq-score-meta"><span>${esc(dateText(e.date))}</span><span>${esc((e.broadcasts||[])[0]||'ESPN')}</span></div><div class="ghq-score-status">${esc(status(e))}</div>${row(a)}${row(h)}<div class="ghq-score-bottom"><span>${esc(e.venue||'')}</span><span>${esc(e.city||'')}${e.state?`, ${esc(e.state)}`:''}</span></div></a>`}
  function renderWeek(wd,rankings,weekLabel){const top=document.getElementById('fcs-top20'),big=document.getElementById('bigsky-score-games');if(!top||!big)return;top.className='ghq-score-section';big.className='ghq-score-section';const games=(wd.fcsTop25Games||[]);top.innerHTML=games.length?`<div class="ghq-score-grid">${games.map(e=>eventCard(e,rankings)).join('')}</div>`:`<div class="ghq-score-empty"><strong>NO TOP 25 FCS GAMES FOUND</strong><span>${esc(weekLabel)}</span></div>`;const byes=wd.fcsTop25Byes||[];if(byes.length)top.innerHTML+=`<div class="ghq-score-note"><b>TOP 25 BYES</b></div><div class="ghq-score-byes">${byes.map(x=>`<span class="ghq-score-bye"><b>#${esc(x.rank)}</b>${esc(x.team)}</span>`).join('')}</div>`;const bs=wd.bigSkyGames||[];big.innerHTML=bs.length?`<div class="ghq-score-grid">${bs.map(e=>eventCard(e,rankings)).join('')}</div>`:`<div class="ghq-score-empty"><strong>NO BIG SKY GAMES</strong><span>${esc(weekLabel)}</span></div>`}
  async function load(){const weekEl=document.getElementById('fcs-week-filter'),statusEl=document.getElementById('fcs-status'),refresh=document.getElementById('fcs-refresh');if(!weekEl)return;if(!weekEl.dataset.cleanReady){C.weeks.forEach((w,i)=>{const o=document.createElement('option');o.value=i;o.textContent=w[2];weekEl.appendChild(o)});weekEl.value=String(currentWeek());weekEl.addEventListener('change',load);weekEl.dataset.cleanReady='1'}if(refresh&&!refresh.dataset.cleanBound){refresh.addEventListener('click',load);refresh.dataset.cleanBound='1'}const top=document.getElementById('fcs-top20'),big=document.getElementById('bigsky-score-games');top.innerHTML='<div class="ghq-score-empty"><strong>Loading verified scoreboard…</strong></div>';big.innerHTML='';if(statusEl)statusEl.textContent='Loading verified ESPN cache…';try{const d=await fetch(`scoreboard/scoreboard-data.json?ts=${Date.now()}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()});const wd=d.weeks?.find(x=>x.index===Number(weekEl.value));if(!wd)throw Error('Selected week is not cached yet.');renderWeek(wd,(d.rankings||[]).slice(0,25),wd.label);if(statusEl)statusEl.textContent=`Verified ESPN cache • FCS ${wd.fcsTop25Games?.length||0} games • Big Sky ${wd.bigSkyGames?.length||0} games • ${wd.label}`;const rd=document.getElementById('fcs-rankings-date');if(rd&&d.rankingsDate)rd.textContent=`Stats Perform • ${d.rankingsDate}`}catch(e){top.innerHTML=`<div class="ghq-score-error"><strong>SCOREBOARD DATA UNAVAILABLE</strong><span>${esc(e.message||'Verified scoreboard cache unavailable.')}</span></div>`;big.innerHTML='<div class="ghq-score-error"><strong>SCOREBOARD DATA UNAVAILABLE</strong></div>';if(statusEl)statusEl.textContent='Verified scoreboard cache unavailable';console.error('Griz HQ scoreboard',e)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();
