/* Griz HQ — header score strip. Same local scoreboard cache as main scoreboard. */
(function(){
  'use strict';
  const C=window.GRIZ_SCOREBOARD_CONFIG;if(!C)return;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const clean=s=>String(s||'').replace(/\s*\([^)]*\)\s*$/,'').replace(/\s+/g,' ').trim();
  const norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9]/g,'');
  const teamName=t=>t?.displayName||t?.shortDisplayName||t?.name||t?.short||t?.abbreviation||'Team';
  const logo=t=>t?.logo||(t?.id?`https://a.espncdn.com/i/teamlogos/ncaa/500/${encodeURIComponent(t.id)}.png`:'');
  const dateText=s=>{const d=new Date(s);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('en-US',{month:'short',day:'numeric'})};
  const status=e=>e?.status?.completed?'FINAL':e?.status?.state==='in'?(e.status.shortDetail||'LIVE'):(e?.status?.shortDetail||e?.status?.detail||'SCHEDULED');
  function currentWeek(){const n=new Date();let i=C.weeks.findIndex(w=>n>=new Date(w[0]+'T00:00:00')&&n<=new Date(w[1]+'T23:59:59'));if(i>=0)return i;i=C.weeks.findIndex(w=>new Date(w[0]+'T00:00:00')>n);return i>=0?i:C.weeks.length-1}
  function card(e,rankings){const ts=e.teams||[],a=ts.find(t=>t.homeAway==='away')||ts[0]||{},h=ts.find(t=>t.homeAway==='home')||ts[1]||{};const rank=t=>(rankings.find(r=>norm(r.team)===norm(teamName(t)))||{}).rank||'';const row=t=>`<div class="v2-score-team"><span class="v2-score-team-name">${logo(t)?`<img class="ghq-scorebar-logo" src="${esc(logo(t))}" alt="" loading="lazy" decoding="async">`:''}<span>${rank(t)?`<span class="ghq-scorebar-rank">#${esc(rank(t))}</span> `:''}${esc(teamName(t))}</span><b>${esc(t.score??'—')}</b></div>`;const href=e.id?`https://www.espn.com/college-football/game/_/gameId/${encodeURIComponent(e.id)}`:'#';const live=status(e)!=='FINAL'&&status(e)!=='SCHEDULED';return `<a class="v2-score-card ghq-scorebar-card${live?' featured':''}" href="${href}" target="_blank" rel="noopener"><div class="v2-score-meta"><span>${esc(dateText(e.date))}</span><b>ESPN</b></div><div class="ghq-scorebar-status ${live?'live':''}">${esc(status(e))}</div>${row(a)}${row(h)}</a>`}
  function gamesFor(d,i,group){const w=d.weeks?.find(x=>x.index===i);if(!w)return[];return group==='bigsky'?(w.bigSkyGames||[]):(w.fcsTop25Games||[])}
  async function load(){const games=document.getElementById('score-games'),group=document.getElementById('score-group-select'),week=document.getElementById('score-week-select');if(!games||!group||!week)return;if(!week.dataset.ghqReady){C.weeks.forEach((w,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`Week ${i}`;week.appendChild(o)});week.value=String(currentWeek());week.dataset.ghqReady='1';week.addEventListener('change',load);group.addEventListener('change',load)}games.innerHTML='<div class="v2-score-card v2-score-empty"><strong>Loading scores…</strong></div>';try{const d=await fetch(`scoreboard/scoreboard-data.json?ts=${Date.now()}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()});const list=gamesFor(d,Number(week.value)||0,group.value||'fcs');const rs=(d.rankings||[]).slice(0,25);if(!list.length){games.innerHTML='<div class="v2-score-card v2-score-empty"><strong>No games found</strong><small>Verified ESPN cache contains no games for this selection.</small></div>';return}games.replaceChildren(...list.map(e=>{const div=document.createElement('div');div.innerHTML=card(e,rs);return div.firstElementChild}))}catch(e){games.innerHTML='<div class="v2-score-card v2-score-empty"><strong>Score data unavailable</strong><small>Verified scoreboard cache unavailable.</small></div>';console.error('Griz header scorebar',e)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();
