/* Griz HQ header score scroll — authoritative data-driven renderer. */
(function(){
'use strict';
const C=window.GRIZ_SCOREBOARD_CONFIG||{season:2026,weeks:[['2026-08-27','2026-08-30','WEEK 0 • AUG 27–30'],['2026-09-03','2026-09-06','WEEK 1 • SEP 3–6'],['2026-09-10','2026-09-13','WEEK 2 • SEP 10–13'],['2026-09-17','2026-09-20','WEEK 3 • SEP 17–20'],['2026-09-24','2026-09-27','WEEK 4 • SEP 24–27'],['2026-10-01','2026-10-04','WEEK 5 • OCT 1–4'],['2026-10-08','2026-10-11','WEEK 6 • OCT 8–11'],['2026-10-15','2026-10-18','WEEK 7 • OCT 15–18'],['2026-10-22','2026-10-25','WEEK 8 • OCT 22–25'],['2026-10-29','2026-11-01','WEEK 9 • OCT 29–NOV 1'],['2026-11-05','2026-11-08','WEEK 10 • NOV 5–8'],['2026-11-12','2026-11-15','WEEK 11 • NOV 12–15'],['2026-11-19','2026-11-22','WEEK 12 • NOV 19–22']]},$=id=>document.getElementById(id); const CANONICAL_TEAM_IDS={'Montana':'149','Montana State':'147','South Dakota State':'2571','South Dakota':'233','Idaho':'70','Idaho State':'304','Northern Arizona':'2464','Stetson':'56','Stephen F. Austin':'2617'};
const FALLBACK_RANKINGS=[{rank:1,team:"Montana State"},{rank:2,team:"South Dakota State"},{rank:3,team:"Montana"},{rank:4,team:"Tarleton State"},{rank:5,team:"Illinois State"},{rank:6,team:"North Dakota"},{rank:7,team:"Lehigh"},{rank:8,team:"Rhode Island"},{rank:9,team:"Youngstown State"},{rank:10,team:"South Dakota"},{rank:11,team:"UC Davis"},{rank:12,team:"Stephen F. Austin"},{rank:13,team:"Tennessee Tech"},{rank:14,team:"Austin Peay"},{rank:15,team:"Lamar"},{rank:16,team:"Idaho State"},{rank:17,team:"West Florida"},{rank:18,team:"South Carolina State"},{rank:19,team:"Yale"},{rank:20,team:"Northern Arizona"},{rank:21,team:"William & Mary"},{rank:22,team:"Villanova"},{rank:23,team:"Mercer"},{rank:24,team:"Southern Illinois"},{rank:25,team:"Harvard"}];const clean=s=>String(s??'').replace(/\s*\([^)]*\)\s*$/,'').replace(/\s+/g,' ').trim();
const norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9]/g,'');
const teams=g=>Array.isArray(g?.teams)?g.teams:(Array.isArray(g?.competitors)?g.competitors:[]);
const name=t=>t?.name||t?.displayName||t?.short||t?.abbreviation||'Team';
const names=t=>[t?.name,t?.displayName,t?.short,t?.abbreviation].filter(Boolean);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const logo=t=>{const actual=String(t?.id||''),canonical=CANONICAL_TEAM_IDS[clean(name(t))]||'',id=canonical||actual;return t?.logo&&(!canonical||actual===canonical)?t.logo:(id?'https://a.espncdn.com/i/teamlogos/ncaa/500/'+encodeURIComponent(id)+'.png':'')};
const pre=g=>{const s=g?.status||{};return !(s.completed||s.state==='post'||s.state==='in'||s.name==='STATUS_FINAL'||s.name==='STATUS_IN_PROGRESS');};
const stat=g=>{const s=g?.status||{};if(s.completed||s.state==='post'||s.name==='STATUS_FINAL')return'FINAL';if(s.state==='in'||s.name==='STATUS_IN_PROGRESS')return s.shortDetail||'LIVE';return s.shortDetail||s.detail||'UPCOMING';};
const score=(t,g)=>pre(g)?'—':(t?.score??'—');
function rank(t,rs){const id=String(t?.id||''),canonical=Object.keys(CANONICAL_TEAM_IDS).find(n=>CANONICAL_TEAM_IDS[n]===id)||'';if(canonical){const e=rs.find(r=>norm(r.team||r.name||'')===norm(canonical));if(e)return e.rank||'';}const ns=names(t).map(norm);const e=rs.find(r=>ns.includes(norm(r.team||r.name||'')));return e?.rank||''}
function date(v){const d=new Date(String(v||'').slice(0,10)+'T12:00:00Z');return isNaN(d)?'':d.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}
function card(g,rs){const ts=teams(g),a=ts.find(t=>t.homeAway==='away')||ts[0],h=ts.find(t=>t.homeAway==='home')||ts[1];if(!a||!h)return'';const row=t=>{const r=rank(t,rs),im=logo(t);return '<div class="ghq-scroll-team"><span class="ghq-scroll-team-left">'+(r?'<b class="ghq-scroll-rank">#'+r+'</b>':'')+(im?'<img src="'+esc(im)+'" alt="" loading="lazy">':'')+'<span>'+esc(name(t))+'</span></span><strong>'+esc(score(t,g))+'</strong></div>'};const href=/^\d+$/.test(String(g.id||''))?'https://www.espn.com/college-football/game/_/gameId/'+encodeURIComponent(g.id):'https://www.espn.com/college-football/scoreboard/_/week/3/year/2026/seasontype/2';return '<a class="ghq-scroll-card" href="'+href+'" target="_blank" rel="noopener"><div class="ghq-scroll-meta"><span>'+esc(date(g.date))+'</span><small>'+esc(g.source||'ESPN')+'</small></div>'+row(a)+row(h)+'<div class="ghq-scroll-status">'+esc(stat(g))+'</div></a>'}
function week(){const d=new Date().toISOString().slice(0,10),w=C.weeks||[],i=w.findIndex(x=>d>=x[0]&&d<=x[1]);return i>=0?i:(w.findIndex(x=>x[0]>d)>=0?w.findIndex(x=>x[0]>d):Math.max(0,w.length-1))}
async function data(){if(window.GRIZ_SCOREBOARD_DATA&&Array.isArray(window.GRIZ_SCOREBOARD_DATA.weeks)&&Array.isArray(window.GRIZ_SCOREBOARD_DATA.rankings))return window.GRIZ_SCOREBOARD_DATA;const r=await fetch('scoreboard/scoreboard-data.json?score-scroll='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();if(!Array.isArray(d.weeks)||!Array.isArray(d.rankings))throw Error('invalid scoreboard cache');window.GRIZ_SCOREBOARD_DATA=d;return d}
function arrays(w){return{fcs:Array.isArray(w?.fcsTop25Games)?w.fcsTop25Games:Array.isArray(w?.fcsGames)?w.fcsGames:Array.isArray(w?.events)?w.events:[],big:Array.isArray(w?.bigSkyGames)?w.bigSkyGames:Array.isArray(w?.bigSkyEvents)?w.bigSkyEvents:[]}}
function boot(){styles();const g=$('score-games'),p=document.querySelector('.v2-score-prev'),n=document.querySelector('.v2-score-next'),grp=$('score-group-select'),wk=$('score-week-select');if(!g)return;if(!g.dataset.ghqControls){g.dataset.ghqControls='1';p?.addEventListener('click',e=>{e.preventDefault();g.scrollBy({left:-Math.max(280,g.clientWidth*.8),behavior:'smooth'})});n?.addEventListener('click',e=>{e.preventDefault();g.scrollBy({left:Math.max(280,g.clientWidth*.8),behavior:'smooth'})});g.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)>Math.abs(e.deltaX)){e.preventDefault();g.scrollLeft+=e.deltaY}},{passive:false})}grp?.addEventListener('change',render);wk?.addEventListener('change',render);render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot()
})();