/* Griz HQ header score scroll — authoritative data-driven renderer. */
(function(){
'use strict';
const C=window.GRIZ_SCOREBOARD_CONFIG||{},$=id=>document.getElementById(id);
const clean=s=>String(s??'').replace(/\s*\([^)]*\)\s*$/,'').replace(/\s+/g,' ').trim();
const norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9]/g,'');
const teams=g=>Array.isArray(g?.teams)?g.teams:(Array.isArray(g?.competitors)?g.competitors:[]);
const name=t=>t?.name||t?.displayName||t?.short||t?.abbreviation||'Team';
const names=t=>[t?.name,t?.displayName,t?.short,t?.abbreviation].filter(Boolean);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const logo=t=>t?.logo||t?.logos?.[0]?.href||(t?.id?'https://a.espncdn.com/i/teamlogos/ncaa/500/'+encodeURIComponent(t.id)+'.png':'');
const pre=g=>{const s=g?.status||{};return !(s.completed||s.state==='post'||s.state==='in'||s.name==='STATUS_FINAL'||s.name==='STATUS_IN_PROGRESS');};
const stat=g=>{const s=g?.status||{};if(s.completed||s.state==='post'||s.name==='STATUS_FINAL')return'FINAL';if(s.state==='in'||s.name==='STATUS_IN_PROGRESS')return s.shortDetail||'LIVE';return s.shortDetail||s.detail||'UPCOMING';};
const score=(t,g)=>pre(g)?'—':(t?.score??'—');
function rank(t,rs){const ns=names(t),e=rs.find(r=>ns.some(n=>norm(n)===norm(r.team||r.name||'')));if(e)return e.rank||'';return rs.find(r=>{const rt=clean(r.team||r.name||'').toLowerCase().split(/\s+/);return rt.length>1&&ns.some(n=>{const nt=clean(n).toLowerCase().split(/\s+/);return nt.length>=rt.length&&rt.every((w,i)=>nt[i]===w)})})?.rank||''}
function date(v){const d=new Date(String(v||'').slice(0,10)+'T12:00:00Z');return isNaN(d)?'':d.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}
function card(g,rs){const ts=teams(g),a=ts.find(t=>t.homeAway==='away')||ts[0],h=ts.find(t=>t.homeAway==='home')||ts[1];if(!a||!h)return'';const row=t=>{const r=rank(t,rs),im=logo(t);return '<div class="ghq-scroll-team"><span class="ghq-scroll-team-left">'+(r?'<b class="ghq-scroll-rank">#'+r+'</b>':'')+(im?'<img src="'+esc(im)+'" alt="" loading="lazy">':'')+'<span>'+esc(name(t))+'</span></span><strong>'+esc(score(t,g))+'</strong></div>'};return '<article class="ghq-scroll-card"><div class="ghq-scroll-meta"><span>'+esc(date(g.date))+'</span><small>'+esc(g.source||'ESPN')+'</small></div>'+row(a)+row(h)+'<div class="ghq-scroll-status">'+esc(stat(g))+'</div></article>'}
function week(){const d=new Date().toISOString().slice(0,10),w=C.weeks||[],i=w.findIndex(x=>d>=x[0]&&d<=x[1]);return i>=0?i:(w.findIndex(x=>x[0]>d)>=0?w.findIndex(x=>x[0]>d):Math.max(0,w.length-1))}
async function data(){const r=await fetch('scoreboard/scoreboard-data.json?score-scroll='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);return r.json()}
function arrays(w){return{fcs:Array.isArray(w?.fcsTop25Games)?w.fcsTop25Games:Array.isArray(w?.fcsGames)?w.fcsGames:Array.isArray(w?.events)?w.events:[],big:Array.isArray(w?.bigSkyGames)?w.bigSkyGames:Array.isArray(w?.bigSkyEvents)?w.bigSkyEvents:[]}}
function supplement(gs,i){if(i!==3)return gs;const t=(id,n,s,h)=>({id:String(id),name:n,short:s,homeAway:h,score:'—',logo:'https://a.espncdn.com/i/teamlogos/ncaa/500/'+id+'.png'}),v=[{id:'v-montana-osu',date:'2026-09-19T19:00:00Z',source:'Verified schedule',status:{state:'pre',shortDetail:'Sat, Sep 19'},teams:[t(149,'Montana Grizzlies','Montana','away'),t(204,'Oregon State Beavers','Oregon State','home')]},{id:'v-ysu-sdsu',date:'2026-09-19T19:00:00Z',source:'Verified schedule',status:{state:'pre',shortDetail:'Sat, Sep 19'},teams:[t(2754,'Youngstown State Penguins','Youngstown State','away'),t(2571,'South Dakota State Jackrabbits','South Dakota State','home')]}];const key=g=>String(g.id)+'|'+teams(g).map(t=>norm(name(t))).sort();const have=new Set(gs.map(key));return gs.concat(v.filter(g=>!have.has(key(g))))}
async function render(){const el=$('score-games');if(!el)return;const group=$('score-group-select'),wk=$('score-week-select');if(wk&&!wk.dataset.ghqReady){wk.value=String(week());wk.dataset.ghqReady='1'}el.innerHTML='<div class="ghq-scroll-empty">Loading scores…</div>';try{const d=await data(),i=Number(wk?.value??week()),w=d.weeks.find(x=>Number(x.index)===i)||d.weeks[i];if(!w)throw Error('week missing');const rs=Array.isArray(d.rankings)?d.rankings.slice(0,25):[],a=arrays(w);let gs=group?.value==='bigsky'?a.big:supplement(a.fcs.slice(),i);if(group?.value!=='bigsky'&&rs.length){const rn=new Set(rs.map(r=>norm(r.team||r.name||'')));gs=gs.filter(g=>teams(g).some(t=>names(t).some(n=>rn.has(norm(n)))))}gs=Array.from(new Map(gs.filter(g=>g&&g.id!=null).map(g=>[String(g.id),g])).values()).sort((x,y)=>String(x.date||'').localeCompare(String(y.date||'')));el.innerHTML=gs.length?gs.map(g=>card(g,rs)).join(''):'<div class="ghq-scroll-empty">NO GAMES FOUND FOR THIS WEEK</div>';el.scrollLeft=0}catch(e){console.error('Griz HQ score scroll',e);el.innerHTML='<div class="ghq-scroll-empty">SCORE DATA TEMPORARILY UNAVAILABLE</div>'}}
function styles(){if($('ghq-score-scroll-style'))return;const s=document.createElement('style');s.id='ghq-score-scroll-style';s.textContent='.v2-scorebar{display:flex;align-items:stretch;gap:10px;overflow:hidden}.v2-score-games{display:flex;align-items:stretch;gap:8px;flex:1;min-width:0;overflow-x:auto;overflow-y:hidden;scroll-behavior:smooth;scrollbar-width:none}.v2-score-games::-webkit-scrollbar{display:none}.ghq-scroll-card{flex:0 0 285px;min-width:285px;background:#fff;border:1px solid rgba(107,0,56,.14);border-radius:10px;padding:7px 11px;box-sizing:border-box;color:#151515}.ghq-scroll-meta{display:flex;justify-content:space-between;color:#777;font-size:10px;font-weight:800;margin-bottom:4px}.ghq-scroll-team{display:flex;justify-content:space-between;align-items:center;min-height:31px;border-top:1px solid #eee}.ghq-scroll-team-left{display:flex;align-items:center;gap:6px;min-width:0;font-size:12px;font-weight:800;white-space:nowrap}.ghq-scroll-team-left img{width:25px;height:25px;object-fit:contain;flex:0 0 25px}.ghq-scroll-team-left>span:last-child{overflow:hidden;text-overflow:ellipsis}.ghq-scroll-rank{font-size:10px;color:#6b0038}.ghq-scroll-team strong{font-size:15px}.ghq-scroll-status{font-size:9px;font-weight:900;color:#6b0038;text-transform:uppercase;padding-top:3px}.ghq-scroll-empty{display:flex;align-items:center;justify-content:center;min-width:100%;font-size:12px;font-weight:800;color:#777}.v2-score-prev,.v2-score-next{flex:0 0 48px;z-index:2;cursor:pointer}@media(max-width:900px){.ghq-scroll-card{flex-basis:250px;min-width:250px}}';document.head.appendChild(s)}
function boot(){styles();const g=$('score-games'),p=document.querySelector('.v2-score-prev'),n=document.querySelector('.v2-score-next'),grp=$('score-group-select'),wk=$('score-week-select');if(!g)return;if(!g.dataset.ghqControls){g.dataset.ghqControls='1';p?.addEventListener('click',e=>{e.preventDefault();g.scrollBy({left:-Math.max(280,g.clientWidth*.8),behavior:'smooth'})});n?.addEventListener('click',e=>{e.preventDefault();g.scrollBy({left:Math.max(280,g.clientWidth*.8),behavior:'smooth'})});g.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)>Math.abs(e.deltaX)){e.preventDefault();g.scrollLeft+=e.deltaY}},{passive:false})}grp?.addEventListener('change',render);wk?.addEventListener('change',render);render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot()
})();